# Default configuration. To achieve more accuracy in the compass, periodically
# regenerate. With Heron deployed in water, run
#
#   rosrun heron_bringup calibrate_compass
#
# Heron will rotate slowly for 60 seconds and a new calibration will be
# generated.
#
mag_bias:
     x: 0.278237
     y: 0.115117
     z: -0.866171
     radius: 0.342438
